### ISSUE TITLE
openwrt release

### ISSUE THREAD

**Issue by TriplEight** [svrakitin/go-breitbandmessung#1]
It would be awesome to have it running as a service on the router itself. Less last mile problems, more possibilities of scheduling and getting more consistent data (as opposed to running on a eg laptop that's not slways on).
As a nice to have, it would be great to have some UI and data visualization.

**Comment by svrakitin** [comment]
I don’t think it is possible to run this on the router hardware to power headless Chromium. Personally, I run this as a Kubernetes CronJob on my SBC (Khadas Vim4 running k3s) which just outputs stuff into the mounted local directory.

It is important to understand that this is a less of monitoring tool, but a proof gathering for your german ISP to take action.

**Comment by TriplEight** [comment]
Yeah, Chromium would be at least taking too much space (not mention ram) for the most routers.

**Comment by TriplEight** [comment]
I'll try if it's possible on my rpi3b+ connected to a router
